openapi: 3.0.0
info:
  title: ManitobaInstitutes API
  description: The ManitobaInstitutes API allows users to get university and colleges information within Manitoba, 
               including the name of the university, the date of establish and the number of students in the university.
  version: 1.0.0

paths:
  /institutes/json:
    get:
      summary: Get university and college information
      parameters:
        - in: query
          name: name
          schema:
            type: string
          description: The name of the institution for which the user wants the information.
          required: false
        - in: query
          name: public
          schema:
            type: boolean
          description: Pass true if you want the list of all public institutions in Manitoba, or false for the list of private institutions.
          required: false
        - in: query
          name: city
          schema:
            type: string
          description: The name of the city for which user wants the list of institutions.
          required: false
      responses:
        200:
          description: Successful operation
          content:
            application/json:
              schema:
                oneOf:
                  - type: object
                    properties:
                      institute:
                        $ref: '#/components/schemas/Institute'
                      status:
                        type: string
                  - type: object
                    properties:
                      result:
                        type: array
                        items:
                          $ref: '#/components/schemas/Institute'
                      status:
                        type: string
        400:
          description: Bad request

components:
  schemas:
    Institute:
      type: object
      properties:
        name:
          type: string
          description: Name of the institution
        date_of_establishment:
          type: integer
          description: Date of establishment of the institution
        number_of_attendees:
          type: integer
          description: Number of attendees in the institution
